[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<main.cpp>
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit ILI9341 @ ^1.6.1
    ricmoo/QRCode@^0.0.1

[env:diag]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<diag.cpp>
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit ILI9341 @ ^1.6.1
